- platform: mqtt
  name: "Right Dining Room Light"
  command_topic: "cmnd/right_dining_room_light/power"
  state_topic: "stat/right_dining_room_light/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
