- platform: mqtt
  state_topic: "/nodemcu4/Motion/Motion4"
  name: "bathroom_motion"
  payload_on: 1
  payload_off: 0
  device_class: motion
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  