- platform: mqtt
  state_topic: "/nodemcu5/Motion/Motion5"
  name: "Bedroom_Motion"
  payload_on: 1
  payload_off: 0
  device_class: motion
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  