- platform: mqtt
  state_topic: "/nodemcu6/Motion/Motion6"
  name: "Dining_Room_Motion"
  payload_on: 1
  payload_off: 0
  device_class: motion
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  