language: python

python:
  - "3.6"

before_install:
  - mv travis_secrets.yaml secrets.yaml
  - HA_VERSION=$(<.HA_VERSION)

install:
  - pip3 install homeassistant==${HA_VERSION}

script:
  - hass --script check_config -c . -f
