language: python
python:
  - "3.5.3"
  - "3.6.4"
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
before_install:
  - mv travis_secrets.yaml secrets.yaml
  - touch ./home-assistant_v2.db
  - touch ./android/adbkey
  - touch ./android/adbkey.pub
