homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: America/New_York
  customize: !include_dir_merge_named customize
  customize_glob:
    "sensor.dark_sky_*":
      homebridge_hidden: true

  packages: !include_dir_named packages
  whitelist_external_dirs:
    - !secret config

http:
#  api_password: !secret api_password
#  ssl_certificate: !secret ssl_cert
#  ssl_key: !secret ssl_key
  use_x_forwarded_for: True
  trusted_proxies:
    - 127.0.0.1
  trusted_networks:
    - 192.168.1.0/24
  ip_ban_enabled: true
  login_attempts_threshold: 5
  base_url: !secret base_url

config:

api:

cloud:
  alexa:
    filter:
      include_domains:
        - switch
        - light
        - lock
        - input_boolean
        - input_select
      exclude_domains:
        - device_tracker
        - media_player
        - automation
        - binary_sensor
        - group
        - camera
        - climate
        - scene
        - script
        - sensor
      exclude_entities:
        - light.left_attic_light
        - light.right_attic_light
        - light.left_end_table_lamp
        - light.right_end_table_lamp
        - light.living_room_lamp
        - light.front_porch_light
        - light.downstairs_hall_light
        - light.upstairs_hall_light
        - light.bathroom_light
      include_entities:
        - remote.living_room
        - remote.bedroom
homekit:
  filter:
    include_domains:
      - alarm_control_panel
      - switch
      - light
      - lock
      - input_boolean
      - input_select
    exclude_domains:
      - device_tracker
      - media_player
      - automation
      - binary_sensor
      - group
      - camera
      - climate
      - scene
      - script
      - sensor
    exclude_entities:
      - light.left_attic_light
      - light.right_attic_light
      - light.left_end_table_lamp
      - light.right_end_table_lamp
      - light.living_room_lamp
      - light.front_porch_light
      - light.downstairs_hall_light
      - light.upstairs_hall_light
      - light.bathroom_light
    include_entities:
      - remote.living_room
      - remote.bedroom
  entity_config:
    alarm_control_panel.security_system:
      code: !secret alarm_code
    lock.front_door_deadbolt_60:
      code: !secret front_door_code

speedtestdotnet:
  scan_interval:
    minutes: 35
  monitored_conditions:
    - ping
    - download
    - upload

tts:
  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_key_id
    aws_secret_access_key: !secret aws_secret_access_key
    region_name: 'us-east-1'
    voice: Joanna
    cache: true
  - platform: google

notify:
  - platform: ios
  - name: ios_parents
    platform: group
    services:
      - service: ios_joes_iphone
      - service: ios_savannahs_iphone
  - name: ios_family
    platform: group
    services:
      - service: ios_joes_iphone
      - service: ios_savannahs_iphone
  - platform: nfandroidtv
    name: Fire TV
    host: 192.168.1.17
    transparency: 75%
    interrupt: 0
    fontsize: large
  - platform: alexa_media
    name: alexa_media

#  - name: janet
#    platform: telegram
#    chat_id: !secret chat_id

#telegram_bot:
#  - platform: polling
#    api_key: !secret telegram_api_key
#    allowed_chat_ids:
#     - !secret chat_id
#####################################
#                                   #
#############DEVICES#################
#                                   #
#####################################

#alexa:

wink:

alarm_control_panel:
  platform: manual
  code: !secret alarm_code
  disarm_after_trigger: False
  name: Security System
  pending_time: 60
  trigger_time: 120

octoprint:
  host: !secret octoprint_ip
  api_key: !secret octoprint_api
  bed: true
  number_of_tools: 1

ios:
  push:
    categories:
      - name: all power off
        identifier: 'allpoweroff'
        actions:
          - identifier: 'ALL_POWER_OFF'
            title: 'Power Down The House'
            destructive: yes
      - name: alarm
        identifier: 'alarm'
        actions:
          - identifier: 'TRIGGER_ALARM'
            title: 'Trigger the Alarm'
            destructive: yes
          - identifier: 'DEACTIVATE_ALARM'
            title: 'Deactivate the Alarm'
            destructive: no
      - name: alarm clock
        identifier: 'alarmclock'
        actions:
          - identifier: 'AWAKE'
            title: 'Awake'
            destructive: no
          - identifier: 'SNOOZE'
            title: 'Snooze'
            destructive: yes
      - name: power on the house
        identifier: 'poweronthehouse'
        actions:
          - identifier: 'UNLOCK_FRONT_DOOR'
            title: 'Unlock the Door'
            destructive: no
          - identifier: 'LOCK_FRONT_DOOR'
            title: 'Lock the Door'
            destructive: yes

media_player:
  # - platform: kodi
  #   host: !secret livingroom_host
  #   name: Living Room Kodi
  # - platform: kodi
  #   host: !secret bedroom_host
  #   name: Master Bedroom Kodi
  # - platform: alexa
  #   email: !secret email2
  #   password: !secret normal_password
  #   url: amazon.com
  - platform: firetv
    name: Living Room Fire TV
    host: 192.168.1.17
    adbkey: !secret adbkey
  - platform: floorplan_speaker
    name: Living Room Floorplan Speaker
  - platform: floorplan_speaker
    name: Bedroom Floorplan Speaker
  - platform: emby
    host: 192.168.1.9
    api_key: !secret emby_api_key
    auto_hide: true

alexa_media:
  accounts:
    - email: !secret email2
      password: !secret normal_password
      url: amazon.com
      scan_interval: 30

vera:
  vera_controller_url: !secret vera_ip

# tuya:
#   username: !secret phone
#   password: !secret normal_password
#   country_code: 1

#emulated_hue:
#  host_ip: !secret alexa_host_ip
#  expose_by_default: true
#  exposed_domains:
#  - light
#  - switch
#  - input_boolean
#  - media_player

coinbase:
  api_key: !secret coinbase_api
  api_secret: !secret coinbase_secret
  exchange_rate_currencies:
    - LTC

ifttt:
  key: !secret ifttt_api_key

counter:
  motion_activated:
    step: 1
    icon: mdi:history

remote:
  - platform: harmony
    name: Living Room
    host: !secret harmony_host
    activity: Fire TV
  - platform: harmony
    name: Bedroom
    host: !secret harmony_host2
    activity: TV

arlo:
  username: !secret arlo_email
  password: !secret arlo_pass

#dominos:
#  country_code: us
#  first_name: !secret first_name
#  last_name: !secret last_name
#  email: !secret email
#  phone: !secret phone
#  address: !secret address
#  show_menu: 1
#  orders:
#  - name: Medium Pan
#    codes:
#      - P12IPAZA

camera:
  - platform: arlo
  - platform: foscam
    ip: !secret foscam_ip
    name: Bedroom Cam
    username: !secret foscam_user
    password: !secret foscam_pass
    port: !secret foscam_port
  - platform: mjpeg
    mjpeg_url: !secret octoprint_camera_ip
    name: Octoprint Cam
  - platform: generic
    name: Weather Radar
    still_image_url: !secret radar_still_image_url

weather:
  - platform: darksky
    api_key: !secret darksky_api

ffmpeg:

#panel_iframe:
#  dashboard:
#    title: 'HADashboard'
#    url: 'http://192.168.1.9:5050/main_dash'
#    icon: mdi:apps

panel_custom:
#  - name: dominos
#    sidebar_title: Dominos
#    sidebar_icon: mdi:pizza
#    url_path: dominos
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    # config: !include /local/custom_ui/floorplan/floorplan.yaml

mqtt:
  broker: !secret mqtt_broker
  port: 1883
  client_id: home-assistant-1
  username: !secret mqtt_username
  password: !secret mqtt_password
  # discovery: true
  # discovery_prefix: homeassistant

ecobee:
  api_key: !secret ecobee_api_key

####################################
#                                  #
############PRESENCE TRACKER########
#                                  #
####################################

device_tracker:
  - platform: tile
    username: !secret email
    password: !secret normal_password
  - platform: nmap_tracker
    hosts: 192.168.1.1-100
    home_interval: 10
    exclude:
      - 192.168.1.9
      - 192.168.1.11
      - 192.168.1.15
      - 192.168.1.71
      - 192.168.1.72
      - 192.168.1.73
      - 192.168.1.74
      - 192.168.1.77

####################################
#                                  #
############INCLUDES################
#                                  #
####################################

binary_sensor: !include_dir_merge_list binary_sensors
sensor: !include_dir_merge_list sensors
group: !include_dir_merge_named groups
automation: !include_dir_merge_list automations
input_number: !include_dir_merge_named input_numbers
input_select: !include_dir_merge_named input_selects
input_boolean: !include_dir_merge_named input_booleans
script: !include_dir_merge_named scripts
switch: !include_dir_merge_list switches
shell_command: !include_dir_merge_named shell_commands
light: !include_dir_merge_list lights
scene: !include_dir_merge_list scenes
intent_script: !include_dir_merge_named alexa_intents/

shopping_list:

wake_on_lan:

custom_updater:
  track:
    - cards
    - components
    - python_scripts
  component_urls:
    - https://raw.githubusercontent.com/keatontaylor/custom_components/master/custom_components.json
####################################
#                                  #
############ENABLES#################
#                                  #
####################################

zone: !include zones.yaml
discovery:
conversation:
history:
logbook:
logger: !include logger.yaml
sun:
system_health:
frontend:
  themes: !include_dir_merge_named themes/
  # extra_html_url:
  #   - /local/custom_ui/state-card-floorplan.html

updater:
  include_used_components: true

recorder: !include recorder.yaml
#  include:
#    domains:
#      - light
#      - sensor
#      - switch
#      - media_player
