day_mode:
  name: Day Mode
  icon: mdi:weather-sunset-up

night_mode:
  name: Night Mode
  icon: mdi:weather-sunset-down

sleep_mode:
  name: Sleep Mode
  icon: mdi:sleep

shutdown_mode:
  name: Shutdown Mode
  icon: mdi:power
  initial: off
  
school_mode:
  name: School Mode
  icon: mdi:school

alarm_mode:
  name: Alarm Mode
  icon: mdi:shield-home

alarm_triggered:
  name: Alarm Triggered
  icon: mdi:alarm-light
  initial: off

power:
  name: Power
  icon: mdi:power

test_mode:
  name: Test
  initial: off
  icon: mdi:power

just_arrived:
  name: Just Arrived
  initial: off
