- alias: N Start Up
  id: n_start_up
  trigger:
    - event: start
      platform: homeassistant

  action:
    - service: script.speech_engine
      data:
        call_no_announcement: 1
        call_start_up: 1
