- alias: Notification Start Up
  id: notification_start_up
  trigger:
    - event: start
      platform: homeassistant

  action:
    - service: script.speech_engine
      data:
        call_start_up: 1
        ios_title: "Start Up"
