- platform: rest
  resource: http://www.webcal.fi/cal.php?id=335&format=json&start_year=current_year&end_year=current_year&tz=America%2FNew_York
  name: Flag
  scan_interval: 14400
  value_template: >-
    {%- set now_string = now().strftime('%Y-%m-%d') %}
    {% for day_val in value_json if day_val.date == now_string  %}
      True
      {% else %}
      False
    {% endfor -%}
