- platform: github
  access_token: !secret github_access_token
  repositories:
    - path: 'home-assistant/home-assistant'
    - path: '3vasi0n89/home-assistant-config-files'
      name: My Github Config
    - path: '3vasi0n89/Home-Assistant-Notification-Center-Hub'
