- platform: mqtt
  state_topic: "tele/multisensor_kitchen/SENSOR"
  name: "Kitchen Temperature"
  unit_of_measurement: "°F"
  value_template: '{{ value_json.AM2301.Temperature | round(1) }}'

- platform: mqtt
  state_topic: "tele/multisensor_kitchen/SENSOR"
  name: "Kitchen Humidity"
  unit_of_measurement: "%"
  value_template: '{{ value_json.AM2301.Humidity | round(1) }}'
