- platform: mqtt
  state_topic: "saraah/sensornode1"
  name: "SN1 Real Feel"
  unit_of_measurement: "°F"
  value_template: '{{ value_json.heatIndex | round(1) }}'
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  