- platform: mqtt
  state_topic: dummy/floorplan/sensor
  name: Floorplan

- platform: mqtt
  state_topic: floorplan/kiosk/living_room
  name: Living Room Tablet

- platform: mqtt
  state_topic: floorplan/kiosk/bedroom
  name: Bedroom Tablet

- platform: mqtt
  state_topic: floorplan/kiosk/living_room/motion
  name: Living Room Tablet Motion

- platform: mqtt
  state_topic: floorplan/kiosk/living_room/plugged
  name: Living Room Tablet Plugged

- platform: mqtt
  state_topic: floorplan/kiosk/bedroom/motion
  name: Bedroom Tablet Motion

- platform: mqtt
  state_topic: floorplan/kiosk/bedroom/plugged
  name: Bedroom Tablet Plugged
