day_mode:
  name: Day Mode
  icon: mdi:weather-sunset-up
  initial: off
  
night_mode:
  name: Night Mode
  icon: mdi:weather-sunset-down
  initial: off
  
sleep_mode:
  name: Sleep Mode
  icon: mdi:sleep
  initial: off
  
shutdown_mode:
  name: Shutdown Mode
  icon: mdi:power
  initial: off
  
school_mode:
  name: School Mode
  icon: mdi:school
  initial: off

alarm_mode:
  name: Alarm Mode
  icon: mdi:security-home
  initial: off
  
alarm_triggered:
  name: Alarm Triggered
  icon: mdi:alarm_light
  initial: off

power:
  name: Power
  icon: mdi:power
  initial: off
  
test_mode:
  name: Test
  initial: off
  icon: mdi:power

test3:
  name: Test 3
  initial: off
  icon: mdi:power