- platform: mqtt  
  state_topic: "saraah/sensornode2"  
  name: "SN2 Temperature"  
  unit_of_measurement: "°F"  
  value_template: '{{ value_json.temperature | round(1) }}' 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  