- platform: mqtt
  state_topic: "/nodemcu4/Temperature/Temperature"
  name: "bathroom_temperature"
  unit_of_measurement: "°F"
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  