- platform: mqtt  
  state_topic: "saraah/sensornode1"  
  name: "SN1 Humidity"  
  unit_of_measurement: "%"  
  value_template: '{{ value_json.humidity | round(1) }}'
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  