- platform: template
  sensors:
    number_of_lights_on:
      entity_id:
        - light.downstairs_hall_light
        - light.living_room_lamp
        - light.bathroom_light
        - light.left_end_table_lamp
        - light.right_end_table_lamp
        - light.upstairs_hall_light
        - light.left_attic_light
        - light.right_attic_light
        - switch.left_dining_room_light
        - switch.right_dining_room_light
        - switch.christmas_tree_lights
        - light.front_porch_light
      value_template: >-
        {% for state in states if ( 'light' in state.entity_id and state.domain in ['light','switch'] and state.state == 'on' ) -%}
              {% if loop.last -%}
              {{ loop.index - 1}}
              {%- endif %}
              {% else %}
                  0
        {%- endfor %}